// Core Platform Components (Root & Hubs)
export { default as Dashboard } from './dashboards/Dashboard'
export { default as Profile } from './Profile'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as GenericDashboard } from './dashboards/GenericDashboard'
export { default as HubDashboard } from './dashboards/HubDashboard'
export { default as UserDashboard } from './dashboards/UserDashboard'
export { default as AnalyticsDashboard } from './dashboards/AnalyticsDashboard'
export * from './dashboards/CategoryDashboards'
export { default as SettingsHub } from './dashboards/SettingsHub'
export * from './settings'

// Primary Category Star Exports (The 10 Sections)
export * from './image'
export * from './avatar'
export * from './speech'
export * from './text'
export * from './studio'
export * from './video-ai'
export * from './files'
export * from './pdf'
export * from './developers'
export * from './social-media'
export * from './marketing'
export * from './ebook'
export * from './about-us'

// Subsection Tabs & Layouts
export * as ProfileTabs from './profile_sub/tabs' 
